import os
from pathlib import Path

SETTINGS_PATH = Path(os.getenv("SETTINGS_PATH", "/config/settings.json"))
SYNC_LOG_PATH = Path(os.getenv("SYNC_LOG_PATH", "/config/sync_log.json"))
REMOVAL_HISTORY_PATH = Path(os.getenv("REMOVAL_HISTORY_PATH", "/config/removal_history.json"))
DISMISSED_PATH = Path(os.getenv("DISMISSED_PATH", "/config/dismissed.json"))
RANK_TRACKER_PATH = Path(os.getenv("RANK_TRACKER_PATH", "/config/rank_tracker.json"))
LOG_PATH = Path(os.getenv("LOG_PATH", "/config/app.log"))

DEFAULT_SETTINGS = {
    "radarr_mode": "disabled",
    "sonarr_mode": "disabled",
    "tautulli_mode": "disabled",
    "trakt_client_id": "",
    "radarr_url": "http://radarr:7878",
    "radarr_api_key": "",
    "sonarr_url": "http://sonarr:8989",
    "sonarr_api_key": "",
    "tautulli_url": "http://tautulli:8181",
    "tautulli_api_key": "",
    "root_folder_movies": "/movies",
    "root_folder_series": "/tv",
    "radarr_quality_profile_id": 1,
    "sonarr_quality_profile_id": 1,
    "run_interval_seconds": 86400,
    "tautulli_lookback_days": 30,
    "movie_retention_days": 30,
    "series_retention_days": 30,
    "web_port": 8080,
    "web_password": "",
    "netflix_top_url": "https://top10.netflix.com/",
    "netflix_top_countries": ["us"],
    "pushover_enabled": False,
    "pushover_user_key": "",
    "pushover_api_token": "",
    "deletion_enabled": False,
    "sources": ["trakt"],
    "flixpatrol_country": "United Kingdom",
    "flixpatrol_services": [],
    "flixpatrol_service_types": {},
    "flixpatrol_cache_hours": 6,
    "simulation_mode": False,
    "plex_mode": "disabled",
    "plex_url": "http://plex:32400",
    "plex_token": "",
    "plex_movie_library": "Movies",
    "plex_tv_library": "TV Shows",
    "plex_collection_sync_hours": 2,
}

ENV_VAR_TO_SETTING = {
    "RADARR_MODE": "radarr_mode",
    "RADARR_URL": "radarr_url",
    "RADARR_API_KEY": "radarr_api_key",
    "SONARR_MODE": "sonarr_mode",
    "SONARR_URL": "sonarr_url",
    "SONARR_API_KEY": "sonarr_api_key",
    "TAUTULLI_MODE": "tautulli_mode",
    "TAUTULLI_URL": "tautulli_url",
    "TAUTULLI_API_KEY": "tautulli_api_key",
    "TRAKT_CLIENT_ID": "trakt_client_id",
    "ROOT_FOLDER_MOVIES": "root_folder_movies",
    "ROOT_FOLDER_SERIES": "root_folder_series",
    "RADARR_QUALITY_PROFILE_ID": "radarr_quality_profile_id",
    "SONARR_QUALITY_PROFILE_ID": "sonarr_quality_profile_id",
    "RUN_INTERVAL_SECONDS": "run_interval_seconds",
    "TAUTULLI_LOOKBACK_DAYS": "tautulli_lookback_days",
    "WEB_PORT": "web_port",
    "WEB_PASSWORD": "web_password",
    "PUSHOVER_USER_KEY": "pushover_user_key",
    "PUSHOVER_API_TOKEN": "pushover_api_token",
    "DELETION_ENABLED": "deletion_enabled",
    "PLEX_MODE": "plex_mode",
    "PLEX_URL": "plex_url",
    "PLEX_TOKEN": "plex_token",
    "PLEX_MOVIE_LIBRARY": "plex_movie_library",
    "PLEX_TV_LIBRARY": "plex_tv_library",
    "PLEX_COLLECTION_SYNC_HOURS": "plex_collection_sync_hours",
}
